-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS answers_photos
(
    id integer NOT NULL,
    answer_id integer NOT NULL,
    url text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS answers
(
    id integer NOT NULL,
    question_id integer NOT NULL,
    body character varying(1000) NOT NULL,
    date_written text NOT NULL,
    answerer_name character varying(60) NOT NULL,
    answerer_email character varying(60) NOT NULL,
    reported boolean NOT NULL DEFAULT false,
    helpful integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS questions
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    body character varying(1000) NOT NULL,
    date_written text NOT NULL,
    asker_name character varying(60) NOT NULL,
    asker_email character varying(60) NOT NULL,
    reported boolean NOT NULL DEFAULT false,
    helpful integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS answers_photos
    ADD FOREIGN KEY (answer_id)
    REFERENCES answers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS answers
    ADD FOREIGN KEY (question_id)
    REFERENCES questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;